# name: Pages

# on:
#   push:
#     branches:
#       - main # default branch

# jobs:
#   pages:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - name: è·å–æºç  ğŸ›ï¸
#         uses: actions/checkout@v2
#       - name: Nodeç¯å¢ƒç‰ˆæœ¬ ğŸ—œï¸
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16'
#       - name: Cache NPM dependencies
#         uses: actions/cache@v2
#         with:
#           path: node_modules
#           key: ${{ runner.OS }}-npm-cache
#           restore-keys: |
#             ${{ runner.OS }}-npm-cache
#       - name: å®‰è£…ä¾èµ– âš™ï¸
#         run: npm install
#       - name: æ‰“åŒ… ğŸ—ï¸
#         run: |
#           npm run build
#       - name: éƒ¨ç½² ğŸš€
#         uses: JamesIves/github-pages-deploy-action@v4
#       with:
#         branch: gh-pages 
#         folder: public
#         clean: true
name: éƒ¨ç½² photo ä¸»é¢˜
on:
  push:
    branches: [ main ] 
# æ‰§è¡Œçš„ä¸€é¡¹æˆ–å¤šé¡¹ä»»åŠ¡
jobs:
  build-and-deploy:
    # è¿è¡Œåœ¨è™šæ‹Ÿæœºç¯å¢ƒubuntu-latest
    # https://docs.github.com/zh/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
    - name: è·å–æºç   ğŸ›ï¸
      uses: actions/checkout@v2
    - name: Nodeç¯å¢ƒç‰ˆæœ¬ ğŸ—œï¸
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: å®‰è£…ä¾èµ– âš™ï¸  
      run: npm install
    - name: æ‰“åŒ… ğŸ—ï¸  
      run: |
        npm run build
    - name: éƒ¨ç½² ğŸš€
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages 
        folder: public
        clean: true
